# Generated by Django 5.1.6 on 2025-02-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_area_sqft_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('state', 'district', 'area')},
            },
        ),
    ]
