# Generated by Django 5.1.6 on 2025-02-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image3',
        ),
    ]
